//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesRecordsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesRecord
    {
        public string Region { get; set; }
        public string Country { get; set; }
        public string Item_Type { get; set; }
        public string Sales_Channel { get; set; }
        public string Order_Priority { get; set; }
        public System.DateTime Order_Date { get; set; }
        public int Order_ID { get; set; }
        public System.DateTime Ship_Date { get; set; }
        public int Units_Sold { get; set; }
        public double Unit_Price { get; set; }
        public double Unit_Cost { get; set; }
        public double Total_Revenue { get; set; }
        public double Total_Cost { get; set; }
        public double Total_Profit { get; set; }
    }
}
